FROM dart:stable AS build

WORKDIR /build

COPY aq_schema/pubspec.yaml aq_schema/
COPY aq_schema/lib aq_schema/lib

COPY aq_data_layer/pubspec.yaml aq_data_layer/
COPY aq_data_layer/lib aq_data_layer/lib

COPY aq_data_layer/example/stack/console_client/pubspec.yaml aq_data_layer/example/stack/console_client/
COPY aq_data_layer/example/stack/console_client/ aq_data_layer/example/stack/console_client/

WORKDIR /build/aq_data_layer/example/stack/console_client
RUN dart pub get

ARG ENTRY=main.dart
RUN dart compile exe $ENTRY -o client

FROM debian:bookworm-slim
COPY --from=build /build/aq_data_layer/example/stack/console_client/client /app/client
ENTRYPOINT ["/app/client"]
