FROM dart:stable AS build

WORKDIR /build

COPY aq_schema/pubspec.yaml aq_schema/
COPY aq_schema/lib aq_schema/lib

COPY aq_data_layer/pubspec.yaml aq_data_layer/
COPY aq_data_layer/lib aq_data_layer/lib

COPY aq_data_layer/example/stack/console_client/pubspec.yaml aq_data_layer/example/stack/console_client/
COPY aq_data_layer/example/stack/console_client/main_security.dart aq_data_layer/example/stack/console_client/

WORKDIR /build/aq_data_layer/example/stack/console_client
RUN dart pub get
RUN dart compile exe main_security.dart -o security

FROM debian:bookworm-slim
COPY --from=build /build/aq_data_layer/example/stack/console_client/security /app/security
ENTRYPOINT ["/app/security"]
